runtime: python37

env_variables:
  GOOGLE_CLOUD_PROJECT: "SAMPLE_PROJ_ID"
  GOOGLE_APPLICATION_CREDENTIALS: "./gcs_creds.json"
  CLOUD_SQL_USERNAME: "username"
  CLOUD_SQL_PASSWORD: "password"
  CLOUD_SQL_DATABASE_NAME: "database"
  CLOUD_SQL_CONNECTION_NAME: "127.0.0.1"

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
